"use strict";
exports.__esModule = true;
var demo_1 = require("./demo");
var sort_1 = require("./sort");
var storage = new sort_1.Sort();
var phone1 = new demo_1.Phone("viettel", 1123444);
var phone2 = new demo_1.Phone("vinaphone", 1124545);
var phone3 = new demo_1.Phone("mobifone", 1123442);
var phone4 = new demo_1.Phone("viettel", 1127544);
var phone5 = new demo_1.Phone("vinaphone", 1888345);
var phone6 = new demo_1.Phone("mobifone", 1999342);
storage.setPhone(phone1);
storage.setPhone(phone2);
storage.setPhone(phone3);
storage.setPhone(phone4);
storage.setPhone(phone5);
storage.setPhone(phone6);
console.log(storage.getViettel());
console.log(storage.getVinaphone());
console.log(storage.getMobifone());
